<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="se7en" failures="1" tests="10" name="Results" time="90.531" errors="0" timestamp="06 Dec 2022 18:17:46 GMT">
  <testcase classname="myTestProject1.test.registerTest" name="registerWithoutEmail" time="11.244"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithoutUsername" time="5.795"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithoutPassword" time="4.544"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithWrongConfirmPassword" time="10.684"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithoutConfirmPassword" time="13.14"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithoutCheckBox" time="4.48"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithValidData" time="8.809">
    <failure type="java.lang.AssertionError" message="expected [https://turkishemarket.com/] but found [https://turkishemarket.com/users/registration]">
      <![CDATA[java.lang.AssertionError: expected [https://turkishemarket.com/] but found [https://turkishemarket.com/users/registration]
at myTestProject1.test.registerTest.registerWithValidData(registerTest.java:74)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- registerWithValidData -->
  <testcase classname="myTestProject1.test.registerTest" name="registerWithUnAvailableEmail" time="8.831"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithInvalidEmail" time="8.834"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithInvalidName" time="10.007"/>
</testsuite> <!-- Results -->
