<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="se7en" failures="1" tests="10" name="turkishWebTest" time="174.759" errors="0" timestamp="06 Dec 2022 18:09:22 GMT">
  <testcase classname="myTestProject1.test.registerTest" name="registerWithoutEmail" time="16.083"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithoutUsername" time="10.633"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithoutPassword" time="7.426"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithWrongConfirmPassword" time="36.325"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithoutConfirmPassword" time="6.87"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithoutCheckBox" time="5.183"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithValidData" time="15.292">
    <failure type="java.lang.AssertionError" message="expected [https://turkishemarket.com/] but found [https://turkishemarket.com/users/registration]">
      <![CDATA[java.lang.AssertionError: expected [https://turkishemarket.com/] but found [https://turkishemarket.com/users/registration]
at myTestProject1.test.registerTest.registerWithValidData(registerTest.java:74)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- registerWithValidData -->
  <testcase classname="myTestProject1.test.registerTest" name="registerWithUnAvailableEmail" time="13.201"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithInvalidEmail" time="24.659"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithInvalidName" time="35.616"/>
</testsuite> <!-- turkishWebTest -->
